nohup python planning_n_args.py --root_dir /mnt/sda/queenie2/av1_dataset/train/data --save_dir ./data_av1/save_train_frenet/train/  --start_num 0  --end_num  8820 >a_train_0.out 2>&1 & 
nohup python planning_n_args.py --root_dir /mnt/sda/queenie2/av1_dataset/train/data --save_dir ./data_av1/save_train_frenet/train/  --start_num 8820  --end_num  17640 >a_train_1.out 2>&1 & 
nohup python planning_n_args.py --root_dir /mnt/sda/queenie2/av1_dataset/train/data --save_dir ./data_av1/save_train_frenet/train/  --start_num 17640  --end_num  26460 >a_train_2.out 2>&1 & 
nohup python planning_n_args.py --root_dir /mnt/sda/queenie2/av1_dataset/train/data --save_dir ./data_av1/save_train_frenet/train/  --start_num 26460  --end_num  35280 >a_train_3.out 2>&1 & 
nohup python planning_n_args.py --root_dir /mnt/sda/queenie2/av1_dataset/train/data --save_dir ./data_av1/save_train_frenet/train/  --start_num 35280  --end_num  44100 >a_train_4.out 2>&1 & 
nohup python planning_n_args.py --root_dir /mnt/sda/queenie2/av1_dataset/train/data --save_dir ./data_av1/save_train_frenet/train/  --start_num 44100  --end_num  52920 >a_train_5.out 2>&1 & 
nohup python planning_n_args.py --root_dir /mnt/sda/queenie2/av1_dataset/train/data --save_dir ./data_av1/save_train_frenet/train/  --start_num 52920  --end_num  61740 >a_train_6.out 2>&1 & 
nohup python planning_n_args.py --root_dir /mnt/sda/queenie2/av1_dataset/train/data --save_dir ./data_av1/save_train_frenet/train/  --start_num 61740  --end_num  70560 >a_train_7.out 2>&1 & 
nohup python planning_n_args.py --root_dir /mnt/sda/queenie2/av1_dataset/train/data --save_dir ./data_av1/save_train_frenet/train/  --start_num 70560  --end_num  79380 >a_train_8.out 2>&1 & 
nohup python planning_n_args.py --root_dir /mnt/sda/queenie2/av1_dataset/train/data --save_dir ./data_av1/save_train_frenet/train/  --start_num 79380  --end_num  88200 >a_train_9.out 2>&1 & 
nohup python planning_n_args.py --root_dir /mnt/sda/queenie2/av1_dataset/train/data --save_dir ./data_av1/save_train_frenet/train/  --start_num 88200  --end_num  97020 >a_train_10.out 2>&1 & 
nohup python planning_n_args.py --root_dir /mnt/sda/queenie2/av1_dataset/train/data --save_dir ./data_av1/save_train_frenet/train/  --start_num 97020  --end_num  105840 >a_train_11.out 2>&1 & 
nohup python planning_n_args.py --root_dir /mnt/sda/queenie2/av1_dataset/train/data --save_dir ./data_av1/save_train_frenet/train/  --start_num 105840  --end_num  114660 >a_train_12.out 2>&1 & 
nohup python planning_n_args.py --root_dir /mnt/sda/queenie2/av1_dataset/train/data --save_dir ./data_av1/save_train_frenet/train/  --start_num 114660  --end_num  123480 >a_train_13.out 2>&1 & 
nohup python planning_n_args.py --root_dir /mnt/sda/queenie2/av1_dataset/train/data --save_dir ./data_av1/save_train_frenet/train/  --start_num 123480  --end_num  132300 >a_train_14.out 2>&1 & 
nohup python planning_n_args.py --root_dir /mnt/sda/queenie2/av1_dataset/train/data --save_dir ./data_av1/save_train_frenet/train/  --start_num 132300  --end_num  141120 >a_train_15.out 2>&1 & 
nohup python planning_n_args.py --root_dir /mnt/sda/queenie2/av1_dataset/train/data --save_dir ./data_av1/save_train_frenet/train/  --start_num 141120  --end_num  149940 >a_train_16.out 2>&1 & 
nohup python planning_n_args.py --root_dir /mnt/sda/queenie2/av1_dataset/train/data --save_dir ./data_av1/save_train_frenet/train/  --start_num 149940  --end_num  158760 >a_train_17.out 2>&1 & 
nohup python planning_n_args.py --root_dir /mnt/sda/queenie2/av1_dataset/train/data --save_dir ./data_av1/save_train_frenet/train/  --start_num 158760  --end_num  167580 >a_train_18.out 2>&1 & 
nohup python planning_n_args.py --root_dir /mnt/sda/queenie2/av1_dataset/train/data --save_dir ./data_av1/save_train_frenet/train/  --start_num 167580  --end_num  176400 >a_train_19.out 2>&1 & 
nohup python planning_n_args.py --root_dir /mnt/sda/queenie2/av1_dataset/train/data --save_dir ./data_av1/save_train_frenet/train/  --start_num 176400  --end_num  185220 >a_train_20.out 2>&1 & 
nohup python planning_n_args.py --root_dir /mnt/sda/queenie2/av1_dataset/train/data --save_dir ./data_av1/save_train_frenet/train/  --start_num 185220  --end_num  194040 >a_train_21.out 2>&1 & 
nohup python planning_n_args.py --root_dir /mnt/sda/queenie2/av1_dataset/train/data --save_dir ./data_av1/save_train_frenet/train/  --start_num 194040  --end_num  202860 >a_train_22.out 2>&1 & 
nohup python planning_n_args.py --root_dir /mnt/sda/queenie2/av1_dataset/train/data --save_dir ./data_av1/save_train_frenet/train/  --start_num 202860  --end_num  211680 >a_train_23.out 2>&1 & 
